import type { Metadata } from "next";
import "./globals.css";
import { Grid } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Grid
          container
          alignItems="center"
          justifyContent="center"
        >
          <Grid
            item
            container
            maxWidth={980}
            alignItems='center'
            justifyContent='center'
          >
            {children}
          </Grid>
        </Grid>
      </body>
    </html>
  );
}
