import type { Metadata } from "next";
import "./globals.css";
import { Grid, StyledEngineProvider } from "@mui/material";
import Header from "@/src/components/Header";
import { raleway } from "@/src/fonts/raleway";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.variable}>
        <StyledEngineProvider>
          <AppRouterCacheProvider>
            <Grid
              container
              alignItems="center"
              justifyContent="center"
            >
              <Grid
                item
                container
                maxWidth={980}
                alignItems='center'
                justifyContent='center'
              >
                <Header/>
                {children}
              </Grid>
            </Grid>
          </AppRouterCacheProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
